# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20190923_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replyingto',
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commented_on', to='wall_app.Message'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied_to', to='wall_app.User'),
        ),
    ]
