# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-23 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0005_auto_20190923_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='wall_app.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replied_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replier', to='wall_app.Message'),
        ),
    ]
