# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0006_auto_20190923_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replied_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='posted',
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_commented_to', to='wall_app.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replied_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='message_replied_on', to='wall_app.Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='wall_app.User'),
        ),
    ]
