# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-17 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net1', models.CharField(max_length=33)),
                ('net2', models.CharField(max_length=33)),
                ('net3', models.CharField(max_length=33)),
                ('net4', models.CharField(max_length=33)),
                ('net5', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
