# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-17 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTV_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.CharField(max_length=33),
        ),
    ]
