# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-18 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RTV_app', '0003_network_net6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='net6',
            new_name='netshow',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='net1',
            new_name='network',
        ),
        migrations.RemoveField(
            model_name='network',
            name='net2',
        ),
        migrations.RemoveField(
            model_name='network',
            name='net3',
        ),
        migrations.RemoveField(
            model_name='network',
            name='net4',
        ),
        migrations.RemoveField(
            model_name='network',
            name='net5',
        ),
    ]
