# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-16 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20190915_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.ManyToManyField(null=True, related_name='Publishers', to='books_authors_app.Author'),
        ),
    ]
