# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-16 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_auto_20190916_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='Publishers', to='books_authors_app.Book'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='placeholder', max_length=45),
            preserve_default=False,
        ),
    ]
