# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-16 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_auto_20190916_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Notes here'),
            preserve_default=False,
        ),
    ]
