# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-14 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_auto_20190914_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninjas',
            name='dojo_id',
            field=models.IntegerField(),
        ),
    ]
