# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-18 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTV_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
